CREATE DATABASE coffee_shop;
USE coffee_shop;

CREATE TABLE coffee (

  -- TABLE CODE TO GO HERE
id INTEGER NOT NULL AUTO_INCREMENT,
PRIMARY KEY(id),
coffee_name VARCHAR(30),
drink BOOLEAN DEFAULT FALSE
);